### ISSUE TITLE
Group photos into an observation doesn't appear to be working correctly on Windows

### ISSUE THREAD

**Issue by schtibal** [rcloran/lr-inaturalist-publish#15] opened 2024-02-27 12:06 UTC
I've only just started using this plug-in - it's GREAT!  Has required me to rethink my workflow and photo tagging in LR, but for the most part for the better!

I haven't managed to get grouping multiple photos into one observation working properly though. If I select 3 photos and drag them across into the iNaturlist publish collection, then File > Plug-in Extras > Group photos into observation, and then check the Plug-in metadata, all photos have the same Observation UUID. But after a publish operation, I'll still get three observations created, and now each photo has a different Observation UUID.

I think I've done all that I need to, but happy to be told this isn't an issue and I'm just doing something wrong.

**Comment by rcloran** [comment] 2024-02-27 15:23
Glad to hear you've found it useful! What you're describing does sound like an issue -- that's the intended workflow. 

Could you please enable trace logging, do a grouping and upload those images, and then add the resulting logs to this issue? There's some details on how to do that at https://github.com/rcloran/lr-inaturalist-publish/wiki/Logging , let me know if you run into any issues.

Also, which operating system are you on? 0.6.0 made some changes to how UUIDs are generated on Windows so I want to check if that might be related, but since you see the same observation UUID on the photos after grouping I can't quite think how it could be.

**Comment by schtibal** [comment] 2024-02-27 22:07
I'm on Windows 11, and confirmed plugin version 0.6.0.

I just uploaded a pair of photos after enabling trace logging (attached). Not a particularly human friendly log file! I hope it is what you're expecting.

[lr-inaturalist-publish.log](https://github.com/rcloran/lr-inaturalist-publish/files/14426235/lr-inaturalist-publish.log)

**Comment by rcloran** [comment] 2024-02-27 23:30
Thanks, that is the right log file. Yes, it is pretty verbose :) That said, it looks like it doesn't include enough information to diagnose this problem :( I'll try to recreate the issue later this week, and if I can't I'll create a version with more detailed logging for you to try. In the meantime, you may want to turn the trace logging back off, since the log file will otherwise just grow indefinitely.

**Comment by schtibal** [comment] 2024-02-28 02:40
I tried another way, with a few more steps...

Add a single photo to the iNaturalist collection and Publish. Edit the observation on iNaturalist to set the species (and in this case, also manually set the time and GPS co-ords - for some reason even though they are set in LR, neither were pushed to iNaturalist).

Did a sync and verify that the species metadata came back down to LR. Only *then* did I group two more photos into the same observation, then added the 2 new photos into the iNaturalist collection and did another Publish - this time the two new photos were added to the existing collection.

**Comment by rcloran** [comment] 2024-03-01 01:44
I've not been able to recreate the issue (but I've only tried on macOS, I'm not sure what state my Windows testing VM is in). I've created a version for you with some additional logging which may help me figure out where the problem is. If you could give it a try and upload the resulting logs that would be useful.

You can download it at [lr-inaturalist-publish-0.6.1-branch.debug-15.1.g8a7f35f](https://github.com/rcloran/lr-inaturalist-publish/actions/runs/8105198211/artifacts/1287968225) (also linked at the bottom of https://github.com/rcloran/lr-inaturalist-publish/actions/runs/8105198211), and replace the plugin directory with the one in that zip file. Be sure to restart Lightroom, or use the "Reload Plug-in" button in the Plug-In Manager before trying an upload again, and re-enable trace logging if you disabled it. If you need some more detailed instructions, please let me know.

> and in this case, also manually set the time and GPS co-ords - for some reason even though they are set in LR, neither were pushed to iNaturalist

This is kinda curious and suggests that somehow the plugin isn't getting metadata from the LR library. The additional logging I've added will help at least identify if it's getting the UUID that was set...

**Comment by schtibal** [comment] 2024-03-01 02:16
Never mind the lost GPS and timestamp - that was me using the scroll-wheel on the mouse through the plugin configuration dialog, and accidentally changing the metadata config to exclude all metadata from the export!

Updated log attached (I didn't remove it, so it still has the few lines from the other day.

Sequence of events to match up:

1. Group two photos (of a sea dragon) into the same observation
2. Drag both photos into the iNaturalist Publish collection
3. Publish the collection
4. Delete one observation on iNaturalist
5. Back in LR, clear observation metadata from the same photo
6. Group two photos again
7. Sync to update metadata on the second photo.

I stopped the logging at this stage, but marked the second photo for republish, and then republished. The result was as expected - the second photo was added to the existing observation.

As a side note, on sync, in the logfile the matching of 12 photos is on a different observation, where I've grouped a dozen photos into the same observation, but only put two of them into the iNaturalist publish collection. That's a great way to update all my photos with taxonomy data, but still only publishing the photos I want to publish on iNaturalist.

[lr-inaturalist-publish.log](https://github.com/rcloran/lr-inaturalist-publish/files/14455573/lr-inaturalist-publish.log)

**Comment by rcloran** [comment] 2024-03-01 17:21
Thanks! It looks like the API isn't accepting the UUIDs I've generated using the new Windows-specific UUID generator. It looks like I've included a carriage return, not properly handling Windows line endings. I'll dig in to this today/this weekend. 

```

03/01/2024 13:00:40 TRACE	uploadPhoto. observationUUID = 367337ab-1a81-4c1a-98b0-966325bbda28
...

03/01/2024 13:00:45 TRACE	Updated observation with photo metadata: { "faves_count": 0, "cached_votes_total": 0, "observation_field_values": [  ], "id_please": false, "tag_list": [ "Australia", "Divelog", "Diving", "Flinders Pier", "Marine Life", "Sites", "Victoria", "Weedy Seadragon", "dive#0190" ], "time_observed_at_utc": "2021-11-01T03:02:00.000Z", "observed_on_string": "2021-11-01 14:02:00", "user_id": 4405947, "location_is_exact": false, "num_identification_disagreements": 0, "latitude": "-38.4756938883", "observed_on": "2021-11-01", "observation_photos_count": 0, "quality_grade": "casual", "uuid": "367337ab-1a81-4c1a-98b0-966325bbda28\r" ...

03/01/2024 13:00:46 TRACE	createObservation response: { "identifications": [ { "created_at": "2024-03-01T13:00:46+11:00", "uuid": "677bf9d7-3223-42e8-a29a-fba47bf0d961" ...
```



> Sequence of events to match up:

Thanks for including the detailed steps you took -- it does help me make sense of the log :)

**Comment by rcloran** [comment] 2024-03-01 20:20
I think #16 should fix this. I've not tested it end-to-end on Windows, only with constructed strings in a lua REPL. It also adds some more logging around uploads to help identify this sort of bug more easily in the future (with less verbosity than the earlier test build I created for you).

If you could help test it, that would be appreciated. You can get it at [lr-inaturalist-publish-0.6.1-branch.winrnd-cr.2.g376e124](https://github.com/rcloran/lr-inaturalist-publish/actions/runs/8116725333/artifacts/1290503471) or linked at the bottom of https://github.com/rcloran/lr-inaturalist-publish/actions/runs/8116725333 .

**Comment by rcloran** [comment] 2024-03-02 20:05
I set my Windows VM back up and tested #16, and it looks to me like it works, so I've merged it. I'll release 0.6.1 with this fix soon.

**Closed** 2024-03-02 20:04 UTC

**Comment by rcloran** [comment] 2024-03-02 20:10
[0.6.1 is released](https://github.com/rcloran/lr-inaturalist-publish/releases/tag/v0.6.1) with the fix for this issue. You should be prompted to update next time you start Lightroom.

Thanks for the report!

**Comment by schtibal** [comment] 2024-03-04 00:52
@rcloran I've been away for a couple of days so didn't get a chance to test it before you released the fix. But can confirm it works as expected now!
